# Fixtures file hold the dependencies for spec helper
fixtures:
  forge_modules:
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "4.3.0"
    gcc:
      repo: "puppetlabs/gcc"
      ref: "0.3.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
      ref: "1.2.0"
    python:
      repo: "stankevich/python"
      ref: "1.9.4"
    apache:
      repo : "puppetlabs/apache"
      ref: "1.4.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.2" 
    nodejs:
      repo: "puppetlabs/nodejs"
      ref: "0.8.0"
#    yamlfile:
#      repo: "reidmv/yamlfile"
#      ref: "0.2.0"
#    apt:
#      repo: "puppetlabs/apt"
#      ref: "1.7.0"
#  repositories: 
#    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
#    yamlfile: git://github.com/reidmv/puppet-module-yamlfile.git
#    apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    cabot: "#{source_dir}"