HOSTS:
  ubuntu-14-04:
    roles:
      - master
      - agent
    platform: ubuntu-14.04-x64    
    box: puppetlabs/ubuntu-14.04-64-puppet
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet
    hypervisor: vagrant    
#    image: i686/ubuntu
#    hypervisor: docker
#    docker_preserve_image: true
#    docker_image_commands: ['true']
#    docker_cmd: '["false"]'
CONFIG:
  type: aio
#  log_level: verbose
#ssh:
#  password: root
#  auth_methods: ["password"]
  